export const TODO_LISTS_GET_START = 'TODO_LISTS_GET_START';
export const TODO_LISTS_GET_SUCCESS = 'TODO_LISTS_GET_SUCCESS';
export const TODO_LISTS_GET_ERROR = 'TODO_LISTS_GETT_ERROR';

export const TODO_LIST_POST_START = 'TODO_LIST_POST_START';
export const TODO_LIST_POST_SUCCESS = 'TODO_LIST_POST_SUCCESS';
export const TODO_LIST_POST_ERROR = 'TODO_LIST_POST_ERROR';

export const TODO_LIST_REMOVE_START = 'TODO_LIST_REMOVE_START';
export const TODO_LIST_REMOVE_SUCCESS = 'TODO_LIST_REMOVE_SUCCESS';
export const TODO_LIST_REMOVE_ERROR = 'TODO_LIST_REMOVE_ERROR';

export const TODO_LIST_EDIT_START = 'TODO_LIST_EDIT_START';
export const TODO_LIST_EDIT_SUCCESS = 'TODO_LIST_EDIT_SUCCESS';
export const TODO_LIST_EDIT_ERROR = 'TODO_LIST_EDIT_ERROR';

export const TODOS_GET_START = 'TODOS_GET_START';
export const TODOS_GET_SUCCESS = 'TODOS_GET_SUCCESS';
export const TODOS_GET_ERROR = 'TODOS_GETT_ERROR';

export const TODO_POST_START = 'TODO_POST_START';
export const TODO_POST_SUCCESS = 'TODO_POST_SUCCESS';
export const TODO_POST_ERROR = 'TODO_POST_ERROR';


export const TODO_EDIT_START = 'TODO_EDIT_START';
export const TODO_EDIT_SUCCESS = 'TODO_EDIT_SUCCESS';
export const TODO_EDIT_ERROR = 'TODO_EDIT_ERROR';

export const TODO_REMOVE_START = 'TODO_REMOVE_START';
export const TODO_REMOVE_SUCCESS = 'TODO_REMOVE_SUCCESS';
export const TODO_REMOVE_ERROR = 'TODO_REMOVE_ERROR';

export const TODO_CLEAR = 'TODO_CLEAR';